const analysisRouter = {
  name: null,
  title: '详细分析',
  type: 'folder',
  icon: 'iconfont icon-erjituandui',
  order: 4,
  inNav: true,
  children: [
    {
      title: '基础分析',
      type: 'view',
      name: 'secBasic',
      route: '/investment/secBasic-list',
      filePath: 'view/investment/secBasic-list.vue',
      inNav: true,
      icon: 'iconfont icon-quan',
    },
    {
      title: '财务分析',
      type: 'view',
      name: 'finAnalysis',
      route: '/investment/finAnalysis-list',
      filePath: 'view/investment/finAnalysis-list.vue',
      inNav: true,
      icon: 'iconfont icon-quan',
    },
    {
      title: '估值分析',
      type: 'view',
      name: 'stockValue',
      route: '/investment/stockValue-list',
      filePath: 'view/investment/stockValue-list.vue',
      inNav: true,
      icon: 'iconfont icon-quan',
    },
    {
      title: '杜邦分析',
      type: 'view',
      name: 'dupontAnalysis',
      route: '/investment/dupontAnalysis-list',
      filePath: 'view/investment/dupontAnalysis-list.vue',
      inNav: true,
      icon: 'iconfont icon-quan',
    },
    {
      title: '成长分析',
      type: 'view',
      name: 'growth',
      route: '/investment/growth-list',
      filePath: 'view/investment/growth-list.vue',
      inNav: true,
      icon: 'iconfont icon-quan',
    },
    {
      title: '行业分类',
      type: 'view',
      name: 'industryClass',
      route: '/investment/industryClass-list',
      filePath: 'view/investment/industryClass-list.vue',
      inNav: true,
      icon: 'iconfont icon-quan',
    },
    {
      title: '核心指标历史',
      type: 'view',
      name: 'coreIndexHist',
      route: '/investment/coreIndexHist-list',
      filePath: 'view/investment/coreIndexHist-list.vue',
      inNav: true,
      icon: 'iconfont icon-quan',
    },
  ],
}

export default analysisRouter
